// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://sokjzlflynpfccmnvnac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNva2p6bGZseW5wZmNjbW52bmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMzIyOTksImV4cCI6MjA4NTYwODI5OX0.2FiOeovtvy90Grs38LS9LFb--f0ArkdoDS5EdORIOik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);